discussions/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.DiscussionTopicListView.as_view(),
         name='discussion_topic_list'),

    path('<topic_id>/posts/',
         views.DiscussionPostListView.as_view(), name='post_list'),

    path('<topic_id>/posts/<post_id>/',
         views.DiscussionPostDetailView.as_view(), name='post_detail'),

    path('<int:pk>/',
         views.DiscussionTopicDetailView.as_view(),
         name='discussion_topic_detail'),
    path('mine/',
         views.ManageDiscussionListView.as_view(),
         name='manage_discussion_topic_list'),

    path('create/',
         views.DiscussionCreateView.as_view(),
         name='discussion_topic_create'),

    path('<pk>/edit/',
         views.DiscussionUpdateView.as_view(),
         name='discussion_topic_edit'),

    path('<pk>/delete/',
         views.DiscussionDeleteView.as_view(),
         name='discussion_topic_delete'),

    path('<pk>/post/',
         views.DiscussionPostUpdateView.as_view(),
         name='discussion_topic_post_update'),

    path('subject/<slug:subject>)/',
         views.DiscussionTopicListView.as_view(),
         name='discussion_topic_list_subject'),

    path('subject/<slug:subject>)/<order>/',
         views.DiscussionTopicListView.as_view(),
         name='discussion_topic_list_subject'),

    path('school_level/<slug:school_level>/<order>/',
         views.DiscussionTopicListView.as_view(),
         name='discussion_topic_list_level'),

    path('school_level/<slug:school_level>/subject/<slug:subject>)/<order>/',
         views.DiscussionTopicListView.as_view(),
         name='discussion_topic_list_level_subject'),

    path('discussion_topic/<int:pk>/',
         views.DiscussionTopicDetailView.as_view(),
         name='discussion_topic_detail'),

    path('<order>',
         views.DiscussionTopicListView.as_view(),
         name='discussion_topic_list'),

    path('all_posts/',
         views.AllPostListView.as_view(),
         name="all_posts")
]

elearn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('main.urls')),
    path('administrator/', include('administers.urls')),
    path('users/', include('users.urls')),
    path('courses/', include('courses.urls')),
    path('notes/', include('notes.urls')),
    path('users/', include('users.urls')),
    path('quizzes/', include('quizzes.urls')),
    path('discussions/', include('discussions.urls')),
    path('api/',	include('courses.api.urls',	namespace='courses_api')),
    path('api/',	include('main.api.urls',	namespace='api')),
    path('api/users/',	include('users.api.urls',	namespace='api_users')),
    path('api/',	include('notes.api.urls',	namespace='notes_api')),
    path('api/',	include('quizzes.api.urls',	namespace='quizzes_api')),
    path('api/',	include('discussions.api.urls',	namespace='discussion_api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

app_name = 'main'

router = routers.DefaultRouter()
router.register('school_levels', views.SchoolLevelViewSet)
router.register('specilisations', views.SpecialisationViewSet)
router.register('programs', views.ProgramViewSet)
router.register('subjects', views.SubjectViewSet)


urlpatterns = [
    path('', include(router.urls)),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.search_all, name='search_all'),
    path('search/<models_list>/', views.search, name='search'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('subscribe/confirm/',
         views.subscribe_confirm, name='subscribe_confirm')
]

discussions/models.py
from django.db import models
from users.models import User
from main.models import SchoolLevel, Subject

# Create your models here.


class DiscussionTopic(models.Model):
    owner = models.ForeignKey(
        User, related_name='discussion_topics', on_delete=models.SET_NULL, null=True)
    subject = models.ForeignKey(Subject,
                                related_name='discussion_topics',
                                on_delete=models.CASCADE)
    school_level = models.ForeignKey(SchoolLevel,
                                     related_name='discussion_topics',
                                     on_delete=models.CASCADE)
    title = models.CharField(max_length=254)
    description = models.TextField(blank=True)
    cover_img = models.ImageField(
        upload_to='discussions/images/', default='discussions/images/topic_default.jpg')
    tags = models.TextField(blank=True)
    verified = models.IntegerField(default=1)

    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.title}_{self.pk}'


class Post(models.Model):
    owner = models.ForeignKey(
        User, related_name='posts', on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=1000)
    post_content = models.TextField(blank=True)
    discussion_topic = models.ForeignKey(
        DiscussionTopic, related_name='posts', on_delete=models.SET_NULL, null=True, blank=True)
    image = models.ImageField(
        upload_to="discussions/images/", default="discussions/images/default.png")
    verified = models.IntegerField(default=1)
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.title}_post_{self.pk}'


class Replie(models.Model):
    user = models.ForeignKey(User, related_name='replies',
                             on_delete=models.SET_NULL, null=True, blank=True)
    replie_content = models.TextField()
    post = models.ForeignKey(
        Post, related_name='replies', on_delete=models.CASCADE)
    image = models.ImageField(
        upload_to="discussions/images/", default="discussions/images/default.png")
    verified = models.IntegerField(default=1)
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.post}_reply_{self.user}_{self.pk}'

notes/models.py
from django.db import models
from main.models import Subject, SchoolLevel
from users.models import User, Review
from django.contrib.contenttypes import fields
from django.utils.text import slugify

# Create your models here.


# ====== NOTEMODEL ======
class Note(models.Model):
    owner = models.ForeignKey(User,
                              related_name='notes_uploaded',
                              on_delete=models.SET_NULL, blank=True, null=True)
    school_level = models.ForeignKey(SchoolLevel,
                                     related_name='notes',
                                     on_delete=models.SET_NULL, blank=True, null=True)
    subject = models.ForeignKey(Subject,
                                related_name='notes',
                                on_delete=models.SET_NULL, blank=True, null=True)
    title = models.CharField(max_length=254)
    cover_img = models.ImageField(
        default='notes/images/default.jpg', upload_to='notes/images/')
    description = models.TextField(blank=True)
    body = models.TextField(blank=True)
    file = models.FileField(upload_to='notes/files/', blank=True)
    total_ratings = models.FloatField(default=0.0)
    num_ratings = models.IntegerField(default=0)
    average_rating = models.FloatField(default=0.0)
    downloads = models.CharField(max_length=254, default=0)
    tags = models.TextField(blank=True)
    slug = models.SlugField(max_length=200,	unique=True)
    verified = models.IntegerField(default=0)

    created = models.DateTimeField(auto_now=True)
    students = models.ManyToManyField(
        User, related_name='notes_saved', blank=True)

    reviews = fields.GenericRelation(Review)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title

    def get_average_rating(self):
        if float(self.num_ratings) == 0.0 or float(self.total_ratings) == 0.0:
            return 0.000
        return round(float(self.total_ratings) / float(self.num_ratings), 3)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        self.average_rating = self.get_average_rating()
        super(Note, self).save(*args, **kwargs)

discussions/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from .models import DiscussionTopic,	Post

PostFormSet = inlineformset_factory(DiscussionTopic,
                                    Post,
                                    fields=['discussion_topic',
                                            'title',
                                            'post_content',
                                            'image'],
                                    extra=2,
                                    can_delete=True)

main/forms.py
from django.forms import ModelForm, EmailField, EmailInput, Form
from .models import Contact


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'


class SubscriberForm(Form):
    email = EmailField(label='Your email',
                             max_length=100,
                             widget=EmailInput(attrs={'class': 'form-control'}))

discussions/api/views.py
from pydoc_data.topics import topics
from django.shortcuts import get_object_or_404
from rest_framework import generics
from rest_framework.authentication import BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import viewsets, status
from rest_framework.decorators import action
from .serializers import TopicSerializer, TopicDetailSerializer, PostSerializer, \
    PostDetailSerializer, PostCreateSerializer, TopicCreateSerializer, ReplieCreateSerializer, ReplieSerializer
from ..models import DiscussionTopic, Post, Replie
from courses.models import Subject
from main.mixins import GetSerializerClassMixin
from django.http import Http404


class DiscussionTopicViewSet(GetSerializerClassMixin, viewsets.ModelViewSet):
    queryset = DiscussionTopic.objects.all()
    serializer_class = TopicDetailSerializer
    serializer_action_classes = {
        'list': TopicSerializer,
        'create': TopicCreateSerializer,
        'update': TopicCreateSerializer
    }

    filterset_fields = ("school_level", "subject", "number_of_posts", )
    search_fields = ("title", )
    ordering_fields = ("title", "total_posts", )
    ordering = ("-date", )

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(
            data=request.data, many=isinstance(request.data, list))
        if serializer.is_valid(raise_exception=True):
            validated_data = serializer.validated_data
            DiscussionTopic.objects.create(
                owner=self.request.user,  **validated_data)
        return Response(serializer.data)

    def update(self, request, *args, **kwargs):
        partial = True
        serializer = self.get_serializer(data=request.data, partial=partial)
        if serializer.is_valid(raise_exception=True):
            validated_data = serializer.validated_data
            instance = self.get_object()
            instance.subject = validated_data.get("subject", instance.subject)
            instance.title = validated_data.get("title", instance.title)
            instance.school_level = validated_data.get(
                "school_level", instance.school_level)

            instance.save()

        return Response(serializer.data)

    def destroy(self, request, *args, **kwargs):
        print('delete')
        try:
            instance = self.get_object()
            self.perform_destroy(instance)
        except Http404:
            content = {
                'message': 'discussion topic with given id does not exist'}
            return Response(content, status=status.HTTP_404_NOT_FOUND)
        content = {'message': 'discussion topic deleted successfully'}
        return Response(content, status=status.HTTP_204_NO_CONTENT)


class PostViewSet(GetSerializerClassMixin, viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    serializer_action_classes = {
        'list': PostSerializer,
        'create': PostCreateSerializer,
        'update': PostCreateSerializer,
    }

    filterset_fields = ("discussion_topic", "owner", )
    search_fields = ("title", 'post_content')
    ordering_fields = ("title", "date", "total_replies")
    ordering = ("-date", )

    def get_queryset(self):
        discussion_topic = DiscussionTopic.objects.get(
            id=self.kwargs['topic_id'])
        return Post.objects.filter(discussion_topic=discussion_topic)

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(
            data=request.data, many=isinstance(request.data, list))
        if serializer.is_valid(raise_exception=True):
            validated_data = serializer.validated_data
            discussion_topic = DiscussionTopic.objects.get(
                id=self.kwargs['topic_id'])
            Post.objects.create(owner=request.user,
                                discussion_topic=discussion_topic, **validated_data)
        return Response(serializer.data)

    def update(self, request, *args, **kwargs):
        partial = True
        serializer = self.get_serializer(data=request.data, partial=partial)
        if serializer.is_valid(raise_exception=True):
            validated_data = serializer.validated_data
            instance = self.get_object()
            instance.post_content = validated_data.get(
                "post_content", instance.post_content)
            instance.image = validated_data.get("image", instance.image)

            instance.save()

        return Response(serializer.data)

    def destroy(self, request, *args, **kwargs):
        print('delete')
        try:
            instance = self.get_object()
            self.perform_destroy(instance)
        except Http404:
            content = {'message': 'post with given id does not exist'}
            return Response(content, status=status.HTTP_404_NOT_FOUND)
        content = {'message': 'post deleted successfully'}
        return Response(content, status=status.HTTP_204_NO_CONTENT)


class ReplieViewSet(GetSerializerClassMixin, viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = ReplieSerializer
    serializer_action_classes = {
        'list': ReplieSerializer,
        'create': ReplieCreateSerializer,
        'update': ReplieCreateSerializer,
    }

    filterset_fields = ("post", "user", 'date')
    search_fields = ("replie_content", )
    ordering_fields = ("date", )
    ordering = ("-date", )

    def get_queryset(self):
        post = Post.objects.get(id=self.kwargs['post_id'])
        return Replie.objects.filter(post=post)

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(
            data=request.data, many=isinstance(request.data, list))
        if serializer.is_valid(raise_exception=True):
            validated_data = serializer.validated_data
            post = Post.objects.get(
                id=self.kwargs['post_id'])
            Replie.objects.create(user=request.user,
                                  post=post, **validated_data)
        return Response(serializer.data)

    def update(self, request, *args, **kwargs):
        partial = True
        serializer = self.get_serializer(data=request.data, partial=partial)
        if serializer.is_valid(raise_exception=True):
            validated_data = serializer.validated_data
            instance = self.get_object()
            instance.replie_content = validated_data.get(
                "replie_content", instance.replie_content)
            instance.image = validated_data.get("image", instance.image)

            instance.save()

        return Response(serializer.data)

    def destroy(self, request, *args, **kwargs):
        print('delete')
        try:
            instance = self.get_object()
            self.perform_destroy(instance)
        except Http404:
            content = {'message': 'reply with given id does not exist'}
            return Response(content, status=status.HTTP_404_NOT_FOUND)
        content = {'message': 'reply deleted successfully'}
        return Response(content, status=status.HTTP_204_NO_CONTENT)

main/templates/front/discussions/topic/all_posts.html
{% extends 'front/master.html' %}
{% load static %}

{% block head %}
	<title>All posts</title>
	<link rel="stylesheet" href="{% static 'css/about.css' %}">
	<link rel="stylesheet" href="{% static 'css/discussions/post_list.css' %}">
{% endblock %}

{% block main %}

	<nav aria-label="breadcrumb" style="--bs-breadcrumb-divider: '/';" >
		<ol class="breadcrumb">
		  <li class="breadcrumb-item"><a href="index.html">home</a></li>
		  <li class="breadcrumb-item active" aria-current="page">all posts</li>
		</ol>
	</nav>

	<div class="content" >
		<div>
			<div id="post_success" class="alert alert-success d-flex align-items-center alert-dismissible fade show" style="margin-top: 10px;" role="alert">
				<i style="margin-right: 10px; font-size: 60px;" class="fa-regular fa-circle-check"></i>
				<div>
					<h4 class="alert-heading">Post submitted!</h4>
					<p>You will be notified whenever someone replies to your post</p>
				</div>
				<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4" id="abt_h1_container">
				<h2 id="abt_h1">All Posts</h2>
				<div class="jumbotron">
					<h1 class="display-4">ProjectMajor Disscussion Forum</h1>
					<p class="lead">Welcome to our discussion forum. You can post your question or any related queries by simply clicking on the add post button. <br> Thankyou and Have a nice day!!</p>
					<hr class="my-4">
					<p>You can also reply to others post by clicking on their post and replying them.</p>
					<button class="btn btn-primary btn-lg" data-bs-target="#new_post" data-bs-toggle="modal" role="button">Add Post</button>
				</div>
				<br>
			</div>
			<div class="col-md-8 ">
				{% for post in posts %}
					<div class="card topic_card" >
						<div class="div_top">
							<a href="{% url 'post_detail' topic_id=post.discussion_topic.pk post_id=post.pk %}"><img src="{{ post.image.url }}" class="topic_img"></a>
							<a href="{% url 'post_detail' topic_id=post.discussion_topic.pk post_id=post.pk %}" class="topic_title">{% if post.owner %}{{ post.owner.profile.profile_name }}{% endif %}</a>
							<p class="date small">{{ post.date }} </p>
						</div>
						<hr style="margin: 5px;">
						<h6 class="qns">{{ post.title }}</h6>
						<p class="qns">{{ post.post_content }}?</p>
						<hr style="margin-left: 5px; margin-right: 5px;">
					</div>
				{% endfor %}

				
				<div class="social_icons_abt">
					<a id="fb"><i class="fa-brands fa-facebook-f"></i></a>
					<a id="tw"><i class="fa-brands fa-twitter"></i></a>
					<a id="ig"><i class="fa-brands fa-instagram-square"></i></a>
					<a id="in"><i class="fa-brands fa-linkedin"></i></a>
					<a id="yt"><i class="fa-brands fa-youtube"></i></a>
		
				</div>
			</div>
		</div>

	</div>


	<div class="modal fade" id="new_post" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
		  <div class="modal-content">
			<div class="modal-header">
			  <h5 class="modal-title" id="exampleModalLabel">Add New Post</h5>
			  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
			  <form id="form_new_post" action="" method="POST"> 
				<div class="form-group">
					<label for="post_title">Post Your Question Here</label>
					<input type="text" class="form-control" id="post_title" name="post_title" placeholder="Post Title"></textarea>
				</div>
				<br/>
				<div class="form-group">
					<label for="exampleFormControlTextarea1">Question Full Explanation</label>
					<textarea class="form-control" id="post_content" name="post_content" rows="3" placeholder="Post Content"></textarea>
				</div>
			</div>
		
			<div class="modal-footer">
			  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
			  <button type="submit" class="btn btn-primary">Post</button>
			</div>
		  </div>
		</div>
	</div>

{% endblock%}

{% block script %}

<script>
	$('#form_new_post').submit(function(e){
		e.preventDefault();
		var form = $(e.target)
	
		$.ajax({
			url: '{% url "all_posts" %}',
			type: 'post',
			data: form.serialize(),
			error: function(xhr, ajaxOptions, thrownError){ alert(thrownError); },
			success: function(data){
				if (data.success === true) {
					$('#new_post').modal('toggle');
					$('#post_success').toggleClass('shown')
					window.setTimeout(function() {
						$('#post_success').toggleClass('shown')
					}, 5000);
					
				} 
				else {
					console.log('error')
					alert(`${data.message}`)
				}
				
			}
		})
		})

</script>

{% endblock %}

main/templates/front/discussions/topic/list.html
{% extends 'front/master.html' %}
{% load static %}
{% load index %}

{% block head %}
<title>
	{%	block	title	%}
	{%	if	subject	%}
			{{	subject.title	}}	discussion topics
	{%	else	%}
        All	discussion topics
    {%	endif	%}
{%	endblock	%}
</title>
<link rel="stylesheet" href="{% static 'css/notes/note_list.css' %}">
<link rel="stylesheet" href="{% static 'css/common.css' %}">
<link rel="stylesheet" href="">
{% endblock %}

{% block main %}
<div class="content">
	<nav aria-label="breadcrumb" style="--bs-breadcrumb-divider: '/';">
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a href="{% url 'home' %}">home</a></li>
			<li class="breadcrumb-item active" aria-current="page">discussion</li>
			<li class="breadcrumb-item active" aria-current="page">topics</li>
		</ol>
	</nav>
	<div class="page-heading-container">
		<h1 class="page-heading">
			{%	if	subject	%}
			{{	subject.title	}} Discussion Topics
			{%	else	%}
				All	Discussion Topics
			{%	endif	%} 
		</h1>
		<div class='filter'>
			<div class="btn-group">
				<button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
				  Filter
				</button>
				<ul class="dropdown-menu dropdown-menu-end">
					<li><a class="dropdown-item {%	if not school_level %}selected{%	endif	%}" href="
						{% if subject %}
						{% url 'quiz_list_subject' subject=subject.slug order=order %}
						{% else %}
						{% url 'discussion_topic_list' order=order %}
						{% endif%}">All</a></li>
					<li><hr class="dropdown-divider"></li>
					{% for l in school_levels %}
					<li><a class="dropdown-item {% if	school_level ==	l %}selected{%	endif	%}" href="
						{% if subject %}
						{% url 'discussion_topic_list_level_subject' school_level=l.slug subject=subject.slug order=order %}
						{% else %}
						{% url 'discussion_topic_list_level' school_level=l.slug order=order %}
						{% endif%}
						">{{ l.title }}
						<br><span class="total-item">{{	l.total_quizzes	}} quizzes</span>
					</a></li>
					{% endfor %}
				</ul>
			</div>
			<div class="btn-group">
				<button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
				  Sort 
				</button>
				<ul class="dropdown-menu dropdown-menu-end">
					&nbsp;Date
				  <li><a class="dropdown-item" href="{{ request.path|sort_url:'created' }}">Ascending</a></li>
				  <li><a class="dropdown-item" href="{{ request.path|sort_url:'-created' }}">Descending</a></li>
				  <li><hr class="dropdown-divider"></li>
				  &nbsp;Rating
				  <li><a class="dropdown-item" href="{{ request.path|sort_url:'average_rating' }}">Ascending</a></li>
				  <li><a class="dropdown-item" href="{{ request.path|sort_url:'-average_rating' }}">Descending</a></li>
				</ul>
			</div>
		</div>	
	</div>

    <div class="contents-container">
        <div class="side-bar">
			<h3 class="side-bar-heading">Subjects</h3>
			<ul	id="side-bar-list" class="side-bar-list">
				<li	class="side-bar-list-item {%	if	not	subject	%}selected{%	endif	%}">
					<a	href="{% if school_level %}
						{% url 'discussion_topic_list_level' school_level=school_level.slug order=order %}
						{% else %}
						{% url 'discussion_topic_list' order=order %}
						{% endif %}">All
					</a>
				</li>
				{%	for	s	in	subjects	%}
				<li	class="side-bar-list-item {% if subject == s %}selected{% endif %}">
					<a	href="
						{% if school_level %}
						{% url 'discussion_topic_list_level_subject' school_level=school_level.slug subject=s.slug order=order %}
						{% else %}
						{% url 'discussion_topic_list_subject' subject=s.slug order=order %}
						{% endif %}">
						{{	s.title	}}
						<br><span class="total-item">{{	s.total_discussion_topics	}}	discussion topics</span>
					</a>
				</li>
				{%	endfor	%}
			</ul>
		</div>

		<div class="details-block" id="details-block">
			{%	for	discussion_topic	in	discussion_topics	%}
			{%	with	subject=discussion_topic.subject	%}
			<div class="card">
				<div class="row">
					<h3><a	href="{% url 'discussion_topic_detail' discussion_topic.pk %}">
					{{	discussion_topic.title	}}</a></h3>
					<p>
					<a	href="{% url 'discussion_topic_list_subject' subject.slug %}">
					{{	subject	}}</a>.
					{{	discussion_topic.total_posts	}}	posts.
					Instructor:	{% if discussion_topic.owner != None or discussion_topic.owner != "" %}{{	discussion_topic.owner.profile.profile_name	}} 
					{% else %}Uknown {% endif %}
					</p>
				</div>
			</div>
			{%	endwith	%}
			{% empty %}
					<h3>No discussion topics for {% if school_level %} {{ school_level }} {% endif %}{% if subject %} {{ subject }} {% endif %} yet. Please try another subject!</h3>
			{%	endfor	%}
			<a href="{% url 'discussion_topic_create' %}" style="color: black; text-align:right;"><h5>Upload Quiz</h5></a>
	
			<div class="sub-content">
				<hr>
				<div class="card">
					<div class="card-body" style="display: flex;">
						<div style="margin-right: 5px;">Latest Uploads </div>
					</div>
				</div>
				<div class="row">
					{% for item in latest %}
					<h6>
						 <a href="{% url 'quiz_detail' pk=item.pk %}">{{ forloop.counter }}. {{ item.title }}</a>
					</h6>
				{% endfor %}
					
				</div>
				<div class="card">
					<div class="card-body" style="display: flex;">
						<div style="margin-right: 5px;">Get Notified </div>
					</div>
				</div>
				<div class="subscribe">
					<h3 class="subscribe_txt" >Subscribe</h3>
					<form class="subscribe_form" >
						<input class="subscribe_input" type="email" id="email" name="email" placeholder="Email">
						<button class="subscribe_button" type="submit"><i class="fa fa-arrow-right"></i></button>
					</form>
				</div>
		
				<div class="card">
					<div class="card-body" style="display: flex;">
						<div style="margin-right: 5px;">Tags </div>
					</div>
				</div>
		
				<div class="tags">
					<p class="tag">Zimsec</p>
					<p class="tag">Exam Paper</p>
					<p class="tag">Revision</p>
					<p class="tag">2022</p>
					<p class="tag">Maths</p>
				</div>
		
	
			</div>
		</div>
    </div>
    
</div>
{%	endblock	%}