elearn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('main.urls')),
    path('administrator/', include('administers.urls')),
    path('users/', include('users.urls')),
    path('courses/', include('courses.urls')),
    path('notes/', include('notes.urls')),
    path('users/', include('users.urls')),
    path('quizzes/', include('quizzes.urls')),
    path('discussions/', include('discussions.urls')),
    path('api/',	include('courses.api.urls',	namespace='courses_api')),
    path('api/',	include('main.api.urls',	namespace='api')),
    path('api/users/',	include('users.api.urls',	namespace='api_users')),
    path('api/',	include('notes.api.urls',	namespace='notes_api')),
    path('api/',	include('quizzes.api.urls',	namespace='quizzes_api')),
    path('api/',	include('discussions.api.urls',	namespace='discussion_api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

app_name = 'main'

router = routers.DefaultRouter()
router.register('school_levels', views.SchoolLevelViewSet)
router.register('specilisations', views.SpecialisationViewSet)
router.register('programs', views.ProgramViewSet)
router.register('subjects', views.SubjectViewSet)


urlpatterns = [
    path('', include(router.urls)),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.search_all, name='search_all'),
    path('search/<models_list>/', views.search, name='search'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('subscribe/confirm/',
         views.subscribe_confirm, name='subscribe_confirm')
]

main/models.py
from django.db import models
from phone_field import PhoneField
from django.utils.text import slugify


# Create your models here.


# ======HOME MODEL=======
class Home(models.Model):
    banner_txt = models.CharField(max_length=254)
    slider1_txt = models.CharField(max_length=254)
    tags = models.TextField()
    footer_abt_txt = models.TextField()

    updated = models.DateTimeField(auto_now=True)

    def tags_list(self):
        return self.tags.split(',')

    def __str__(self):
        return f'{self.banner_txt}'


class HomeImage(models.Model):
    home = models.ForeignKey(
        Home, related_name='images', on_delete=models.CASCADE)
    img = models.ImageField(upload_to='home/images/')
    img_heading_txt = models.CharField(max_length=254, blank=True)
    img_txt = models.TextField(blank=True)


# ======ABOUT MODEL======
class About(models.Model):
    heading = models.CharField(max_length=254)
    about_txt = models.TextField()

    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.heading


class AboutImage(models.Model):
    about = models.ForeignKey(
        About, related_name='images', on_delete=models.CASCADE)
    img = models.ImageField(upload_to='about/images/')
    img_txt = models.CharField(max_length=254, default=img.name, blank=True)


class Address(models.Model):
    about = models.ForeignKey(
        About, related_name='addresses', on_delete=models.CASCADE)
    address = models.CharField(max_length=254)


class Email(models.Model):
    about = models.ForeignKey(
        About, related_name='emails', on_delete=models.CASCADE)
    email = models.EmailField(max_length=254)
    primary = models.BooleanField()


class Phone(models.Model):
    about = models.ForeignKey(
        About, related_name='phone_numbers', on_delete=models.CASCADE)
    phone = PhoneField()
    primary = models.BooleanField()


class Social(models.Model):
    about = models.ForeignKey(
        About, related_name='socials', on_delete=models.CASCADE)
    social_name = models.CharField(max_length=254)
    display_title = models.CharField(max_length=254, default='connect with us')
    link = models.URLField(max_length=500, default='#')
    social_font_owesome_icon = models.CharField(max_length=254, blank=True)


# ======CONTACT SECTION======
class Contact(models.Model):
    name = models.CharField(max_length=254, blank=False)
    email = models.EmailField(max_length=254, blank=False)
    message = models.TextField(blank=True)
    seen = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.email


# ======SUBSCRIBE SECTION======
class Subscriber(models.Model):
    email = models.EmailField(unique=True)
    conf_num = models.CharField(max_length=15)
    confirmed = models.BooleanField(default=False)

    def __str__(self):
        return self.email + " (" + ("not " if not self.confirmed else "") + "confirmed)"


# ======SCHOOL LEVEL MODEL======
class SchoolLevel(models.Model):
    title = models.CharField(max_length=254)
    slug = models.SlugField(max_length=254,	unique=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(SchoolLevel, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']


# ======SPECIALISATION MODEL======
class Specialisation(models.Model):
    title = models.CharField(max_length=254)
    slug = models.SlugField(max_length=254,	unique=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Specialisation, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']


# ====== PROGRAM MODEL======
class Program(models.Model):
    title = models.CharField(max_length=254)
    slug = models.SlugField(max_length=254,	unique=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Program, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']


# ======SUBJECT MODEL======
class Subject(models.Model):
    title = models.CharField(max_length=254)
    slug = models.SlugField(max_length=254,	unique=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Subject, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']

main/forms.py
from django.forms import ModelForm, EmailField, EmailInput, Form
from .models import Contact


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'


class SubscriberForm(Form):
    email = EmailField(label='Your email',
                             max_length=100,
                             widget=EmailInput(attrs={'class': 'form-control'}))

main/api/views.py
from rest_framework import generics
from django.shortcuts import get_object_or_404
from rest_framework import generics
from rest_framework.authentication import BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import viewsets, status
from rest_framework.decorators import action
from django.http import Http404
from ..mixins import GetSerializerClassMixin
from ..models import Program, SchoolLevel, Specialisation, Subject
from .serializers import SchoolLevelCreateSerializer, SpecialisationCreateSerializer, SubjectCreateSerializer, SubjectSerializer, \
    ProgramSerializer, SchoolLevelSerializer, SpecialisationSerializer, ProgramCreateSerializer


# ====== SCHOOL LEVEL VIEWSET ======
class SchoolLevelViewSet(GetSerializerClassMixin, viewsets.ModelViewSet):
    queryset = SchoolLevel.objects.all()
    serializer_class = SchoolLevelSerializer
    serializer_action_classes = {
        'create': SchoolLevelCreateSerializer,
        'update': SchoolLevelCreateSerializer,
    }

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(
            data=request.data, many=isinstance(request.data, list))
        if serializer.is_valid(raise_exception=True):
            validated_data = serializer.validated_data
            SchoolLevel.objects.create(**validated_data)
        return Response(serializer.data)

    def update(self, request, *args, **kwargs):
        partial = True
        serializer = self.get_serializer(data=request.data, partial=partial)
        if serializer.is_valid(raise_exception=True):
            validated_data = serializer.validated_data
            instance = self.get_object()
            instance.title = validated_data.get("title", instance.title)

            instance.save()

        return Response(serializer.data)

    def destroy(self, request, *args, **kwargs):
        try:
            instance = self.get_object()
            self.perform_destroy(instance)
        except Http404:
            content = {'message': 'school level with given id does not exist'}
            return Response(content, status=status.HTTP_404_NOT_FOUND)
        content = {'message': 'school level deleted'}
        return Response(status=status.HTTP_204_NO_CONTENT)


# ====== SPECIALISATION VIEWSET ======
class SpecialisationViewSet(GetSerializerClassMixin, viewsets.ModelViewSet):
    queryset = Specialisation.objects.all()
    serializer_class = SpecialisationSerializer
    serializer_action_classes = {
        'create': SpecialisationCreateSerializer,
        'update': SpecialisationCreateSerializer,
    }

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(
            data=request.data, many=isinstance(request.data, list))
        if serializer.is_valid(raise_exception=True):
            validated_data = serializer.validated_data
            Specialisation.objects.create(**validated_data)
        return Response(serializer.data)

    def update(self, request, *args, **kwargs):
        partial = True
        serializer = self.get_serializer(data=request.data, partial=partial)
        if serializer.is_valid(raise_exception=True):
            validated_data = serializer.validated_data
            instance = self.get_object()
            instance.title = validated_data.get("title", instance.title)

            instance.save()

        return Response(serializer.data)

    def destroy(self, request, *args, **kwargs):
        try:
            instance = self.get_object()
            self.perform_destroy(instance)
        except Http404:
            content = {'message': 'specialisation with given id does not exist'}
            return Response(content, status=status.HTTP_404_NOT_FOUND)
        content = {'message': 'specialisation deleted'}
        return Response(content, status=status.HTTP_204_NO_CONTENT)


# ====== PROGRAM VIEWSET ======
class ProgramViewSet(GetSerializerClassMixin, viewsets.ModelViewSet):
    queryset = Program.objects.all()
    serializer_class = ProgramSerializer
    serializer_action_classes = {
        'create': ProgramCreateSerializer,
        'update': ProgramCreateSerializer,
    }

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(
            data=request.data, many=isinstance(request.data, list))
        if serializer.is_valid(raise_exception=True):
            validated_data = serializer.validated_data
            Program.objects.create(**validated_data)
        return Response(serializer.data)

    def update(self, request, *args, **kwargs):
        partial = True
        serializer = self.get_serializer(data=request.data, partial=partial)
        if serializer.is_valid(raise_exception=True):
            validated_data = serializer.validated_data
            instance = self.get_object()
            instance.title = validated_data.get("title", instance.title)

            instance.save()

        return Response(serializer.data)

    def destroy(self, request, *args, **kwargs):
        try:
            instance = self.get_object()
            self.perform_destroy(instance)
        except Http404:
            content = {'message': 'program with given id does not exist'}
            return Response(content, status=status.HTTP_404_NOT_FOUND)

        content = {'message: program deleted'}
        return Response(content, status=status.HTTP_204_NO_CONTENT)


# ====== SUBJECT VIEWSET ======
class SubjectViewSet(GetSerializerClassMixin, viewsets.ModelViewSet):
    queryset = Subject.objects.all()
    serializer_class = SubjectSerializer
    serializer_action_classes = {
        'create': SubjectCreateSerializer,
        'update': SubjectCreateSerializer,
    }

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(
            data=request.data, many=isinstance(request.data, list))
        if serializer.is_valid(raise_exception=True):
            validated_data = serializer.validated_data
            Subject.objects.create(**validated_data)
        return Response(serializer.data)

    def update(self, request, *args, **kwargs):
        partial = True
        serializer = self.get_serializer(data=request.data, partial=partial)
        if serializer.is_valid(raise_exception=True):
            validated_data = serializer.validated_data
            instance = self.get_object()
            instance.title = validated_data.get("title", instance.title)

            instance.save()

        return Response(serializer.data)

    def destroy(self, request, *args, **kwargs):
        try:
            instance = self.get_object()
            self.perform_destroy(instance)
        except Http404:
            content = {'message': 'quiz with given id does not exist'}
            return Response(content, status=status.HTTP_404_NOT_FOUND)
        content = {'message': 'subject deleted'}
        return Response(content, status=status.HTTP_204_NO_CONTENT)

main/templates/front/main/about.html
{% extends 'front/master.html' %}
{% load static %}

{% block head %}
<title>About</title>
<link rel="stylesheet" href="{% static 'css/main/about.css' %}">
{% endblock %}

{% block main %}
	<nav aria-label="breadcrumb" style="--bs-breadcrumb-divider: '/';">
		<ol class="breadcrumb">
		  <li class="breadcrumb-item"><a href="{% url 'home' %}">home</a></li>
		  <li class="breadcrumb-item active" aria-current="page">about</li>
		</ol>
	  </nav>

	<div class="content">
		<div class="row" >
			<h2 id="abt_h2"> {{ about.heading }}</h2>
			<div class="col-md-4" id="abt_h2_container">
				<div class="abt_img" style="display: flex; flex-direction: column; align-items: center;">
					<img id="abt_img" class="" alt="about" src="{{ about.images.first.img.url}}" >
					<p>{{ about.aboutimage_set.first.img_txt}}</p>
				</div>
			</div>
			
			<div class="col-md-8 main_txt">
				<p class="abt_txt">{{ about.about_txt|linebreaks }}
				</p>
				<br/>
				<div class="social_icons_abt">
					{% for social in about.social_set.all %}
					<a id="{% if social.social_name == 'facebook' %}cfb{% elif social.social_name == 'twitter' %}ctw{% elif social.social_name == 'instagram' %}cig{% elif social.social_name == 'linkedin' %}cin{% elif social.social_name == 'youtube' %}cyt{% endif %}"
					 title="{{ social.display_title }}" href="{{ social.link }}">
					 <i class="{{ social.social_font_owesome_icon }}"></i></a>
					{% endfor %}
				</div>
			</div>
		</div>	

	</div>
	
{% endblock%}

{% block script %}
{% endblock %}

main/templates/front/main/contact.html
{% extends 'front/master.html' %}
{% load static %}

{% block head %}
<title>Contact</title>
<link rel="stylesheet" href="{% static 'css/main/contact.css' %}">
{% endblock %}

{% block main %}

<nav aria-label="breadcrumb" style="--bs-breadcrumb-divider: '/';">
	<ol class="breadcrumb">
	  <li class="breadcrumb-item"><a href="{% url 'home' %}">home</a></li>
	  <li class="breadcrumb-item active" aria-current="page">contact</li>
	</ol>
  </nav>

	<div class="content">
		<h2 class="page_hearding " id="contact_h2"> Contact Us</h2>
		<div class="row">
			<div class="col-sm-12 contact_container" >
				<form class="form-horizontal contact_form" action="{% url 'contact' %}" method="post">
					{% csrf_token %}
					{% for field in form %}
						{% if field.name == "name" %}
						<div class="form-group">
							<input class="form-control contact_input" title="Name should not be left blank." type="text" name="name" placeholder="Name*" 
								oninvalid="this.setCustomValidity('Please enter your name')" onkeyup="setCustomValidity('')" required>
						</div>
						{% endif %}
						
						{% if field.name == "email" %}
						<div class="form-group">
							<input class="form-control contact_input" title="Email should not be left blank." type="email" name="email" placeholder="Email*" 
								pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$" 
								oninvalid="setCustomValidity('Please enter a valid email address')" onkeyup="setCustomValidity('')" required>
						</div>
						{% endif %}

						{% if field.name == "message" %}
					
						<div class="form-group">
							<textarea name="message" id="message" cols="0" rows="10" class="form-control contact_input" placeholder="Your Message"
							value="{{ field.value|default_if_none:'' }}"></textarea>
						</div>
						{% endif %}
						{{ field.errors }}
					{% endfor%}
				
					<div class="form-group">
						<input class="button contact_btn" type="submit" value="Submit" >
					</div>
				</form>
				<br/>
				<br/>
				<div style="display: flex; flex-direction: column; align-items: center;">
					<h4>Connect With Us</h4>
					<div class="social_icons">
						{% for social in about.socials.all %}
							<a id="{% if social.social_name.lower == 'facebook' %}cfb{% elif social.social_name.lower == 'twitter' %}ctw{% elif social.social_name.lower == 'instagram' %}cig{% elif social.social_name.lower == 'linkedin' %}cin{% elif social.social_name.lower == 'youtube' %}cyt{% elif social.social_name.lower == 'github' %}cgit{% endif %}"
							title="{{ social.display_title }}" href="{{ social.link }}">
							<i class="{{ social.social_font_owesome_icon }}"></i></a>
						{% endfor %}
					</div>
				</div>
				
			</div>
			
		</div>
		
		
		

	</div>
{% endblock%}

{% block script %}

<script>
	
	$('.contact_form').submit(function(e){
        e.preventDefault();

		$(window).scrollTop(0)
		$('#ajax-loader').show()
		$('#loading-text').text("Please wait...")
		$('body').css({ overflow: 'hidden',height: '100vh' });
		
		var form = $(e.target);
		
        $.ajax({
            url: '{% url "contact" %}',
            type: 'post',
            data: form.serialize(),
            error: function(xhr, ajaxOptions, thrownError){ 
				alert(thrownError); 
				$('#ajax-loader').hide();
			},
            success: function(data){
				if (data.success === true) {
					current_location = window.location.pathname
					txt = current_location.split('/')
					$('#loading-text').text("Message sent")
					$('#ajax-loader').delay(2000).fadeOut()
					
					setTimeout(function(){
						$('#ajax-loader').hide();
						$('body').css({ overflow: 'auto' });
					},2000); 
					alert(`${data.message}`)
					location.reload();
					
				} 
				else {
					alert(`${data.message}`)
					$('#ajax-loader').hide()
					$('body').css({ overflow: 'auto' });
				}
				
				
			}
        })
 	})
	

</script>

{% endblock %}

main/templates/front/main/dashboard.html
{% extends 'front/master.html' %}
{% load static %}

{% block head %}
<title>About</title>
<link rel="stylesheet" href="{% static 'css/about.css' %}">
{% endblock %}

{% block main %}
	<nav aria-label="breadcrumb" style="--bs-breadcrumb-divider: '/';">
		<ol class="breadcrumb">
		  <li class="breadcrumb-item"><a href="/">home</a></li>
		  <li class="breadcrumb-item active" aria-current="page">dashboard</li>
		</ol>
	  </nav>

	<div class="content">
		<div class="row" >
			<h2 id="abt_h2"> {{ about.heading }}</h2>
			<div class="col-md-4" id="abt_h2_container">
				<div class="abt_img" style="display: flex; flex-direction: column; align-items: center;">
					<img id="abt_img" class="" alt="about" src="{{ about.aboutimage_set.first.img.url}}" >
					<p>{{ about.aboutimage_set.first.img_txt}}</p>
				</div>
			</div>
			
			<div class="col-md-8 main_txt">
				<p class="abt_txt">{{ about.about_txt|linebreaks }}
				</p>
				<br/>
				<div class="social_icons_abt">
					{% for social in about.social_set.all %}
					<a id="{% if social.social_name == 'facebook' %}cfb{% elif social.social_name == 'twitter' %}ctw{% elif social.social_name == 'instagram' %}cig{% elif social.social_name == 'linkedin' %}cin{% elif social.social_name == 'youtube' %}cyt{% endif %}"
					 title="{{ social.display_title }}">
					 <i class="{{ social.social_font_owesome_icon }}"></i></a>
					{% endfor %}
				</div>
			</div>
		</div>	

	</div>
	<div class="content_bm" style="text-align: left;">
		<div class="card">
			<div class="card-body" style="display: flex;">
				<div style="margin-right: 5px;">Latest Uploads </div>
			</div>
		</div>
		<div class="latest_sub">
			<div class="latest_sub_item">
				<img class="footer_latest_img" alt="latest" src="{% static 'images/c4.jpg' %}">
				<p>Some latest upload content. Some latest upload content</p>
			</div>
			<br/>
			<div class="latest_sub_item">
				<img class="footer_latest_img" alt="latest" src="{% static 'images/c2.jpg' %}">
				<p>Other latest upload</p>
			</div>
			<br/>
			<div class="latest_sub_item">
				<img class="footer_latest_img" alt="latest" src="{% static 'images/c3.jpg' %}">
				<p>Some latest upload. Some latest upload content</p>
			</div>
			<br/>
			<div class="latest_sub_item">
				<img class="footer_latest_img" alt="latest" src="{% static 'images/c1.jpg' %}">
				<p>Some latest upload. Some latest upload content</p>
			</div>
			<br/>
			
		</div>

	</div>
{% endblock%}

{% block script %}
{% endblock %}

main/templates/front/main/search.html
{% extends 'front/master.html' %}
{% load static %}

{% block head %}
<title>Home | E-Learn</title>
<link rel="stylesheet" href="{% static 'css/common.css' %}">
<link rel="stylesheet" href="{% static 'css/main/search.css' %}">
{% endblock %}

{% block main %}
<div class="content">
	<div class="page-heading-container">
		<h1 class="page-heading">
			Search Results for : "{{ query }}"
		</h1>
	</div>
	{% if results %}
		{% for queryset in results %}
			{% if queryset.model_name == 'Course' %}
				{% for course in queryset %}
				<div class="details-block-item" id="details-block-item">
					<h3 class="details-block-heading"><a href="{% url 'course_detail' slug=course.slug %}">
					{{	course.title	}}</a> <span class="rating">{{ queryset.model_name }}
					</span></h3>
					<p >{% if course.school_level %}
						<a class="details-block-subject" href="{% url 'course_list_level' school_level=course.school_level.slug order='-created' %}">
						{{ course.school_level	}}</a>.{% endif %}
						{% if course.subject %}
						<a class="details-block-subject" href="{% url 'course_list_subject' subject=course.subject.slug order='-created' %}">
						{{	course.subject	}}</a>.{% endif %}
						{{	course.total_modules	}}	modules.
						Instructor:	{% if course.owner %}{{	course.owner.profile.profile_name }} 
						{% else %}Uknown {% endif %}
					</p>
				</div>
				{% endfor %}
			{% elif queryset.model_name == 'Note' %}
				{% for note in queryset %}
				<div class="details-block-item" id="details-block-item">
					<h3 class="details-block-heading"><a href="{% url 'note_detail' slug=note.slug %}">
					{{	note.title	}}</a> <span class="rating">{{ queryset.model_name }}
					</span></h3>
					<p >{% if note.school_level %}
						<a class="details-block-subject" href="{% url 'note_list_level' school_level=note.school_level.slug order='-created' %}">
						{{ note.school_level	}}</a>.{% endif %}
						{% if note.subject %}
						<a class="details-block-subject" href="{% url 'note_list_subject' subject=note.subject.slug order='-created' %}">
						{{	note.subject	}}</a>.{% endif %}
						{{	note.downloads	}}	downloads.
						Upluaded by:	{% if note.owner %}{{	note.owner.profile.profile_name }} 
						{% else %}Uknown {% endif %}
					</p>
				</div>
				{% endfor %}

			{% elif queryset.model_name == 'Quiz' %}
				{% for quiz in queryset %}
				<div class="details-block-item" id="details-block-item">
					<h3 class="details-block-heading"><a href="{% url 'quiz_detail' slug=quiz.slug %}">
					{{	quiz.title	}}</a> <span class="rating">{{ queryset.model_name }}
					</span></h3>
					<p >{% if quiz.school_level %}
						<a class="details-block-subject" href="{% url 'quiz_list_level' school_level=quiz.school_level.slug order='-created' %}">
						{{ quiz.school_level	}}</a>.{% endif %}
						{% if quiz.subject %}
						<a class="details-block-subject" href="{% url 'quiz_list_subject' subject=quiz.subject.slug order='-created' %}">
						{{	quiz.subject	}}</a>.{% endif %}
						{{	quiz.attemps	}}	attemps.
						Upluaded by:	{% if quiz.owner %}{{	quiz.owner.profile.profile_name }} 
						{% else %}Uknown {% endif %}
					</p>
				</div>
				{% endfor %}

			{% elif queryset.model_name == 'DiscussionTopic' %}
				{% for topic in queryset %}
				<div class="details-block-item" id="details-block-item">
					<h3 class="details-block-heading"><a href="{% url 'topic_detail' slug=topic.slug %}">
					{{	topic.title	}}</a> <span class="rating">{{ queryset.model_name }}
					</span></h3>
					
				</div>
				{% endfor %}

			{% elif queryset.model_name == 'Post' %}
				{% for post in queryset %}
				<div class="details-block-item" id="details-block-item">
					<h3 class="details-block-heading"><a href="{% url 'post_detail' topic_id=post.discussion_topic.pk post_id=post.pk %}">
					{{	post.title	}}</a> <span class="rating">{{ queryset.model_name }}
					</span></h3>
				</div>
				{% endfor %}
			
			{% endif %}
		{% endfor %}
	{% else %}
		<h2>No results found for search {{ query }}</h2>
	{% endif %}

	<br>
	<br>
	<div class="banner" >
	
	</div>
	<br>
	<br>

	
	
</div>
{% endblock%}

{% block script %}
<script src="{% static 'js/index.js' %}"></script>
{% endblock %}